version: "3.7"
services:
  postgres:
    container_name: postgres
    restart: always
    image: library/postgres:12
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data/postgres12:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    container_name: the_hero
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=docker
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
#    entrypoint: ["python", "hero_server.py"]